const Messages = {
  NOT_ALL_REQUIRED_FIELDS_MESSAGE: "Oops! It looks like you missed some required fields. Please fill them out.",
  EMAIL_INVALID: 'Email is Invalid!',
  SIGNIN_SUCCESSFULL: 'Signed in successfull',
  USER_DOES_NOT_EXIST: 'User does not Exist',
  USER_CREATION_FAILED: 'User Creation Failed',
  FUll_NAME_INVALID: "Hmm, the full name you entered seems to be invalid. Please provide your complete name.",
  PASSWORD_INVALID: "Uh-oh! The password you entered is invalid. Please try again.",
  PASSWORD_WEEK: "Oh no! Your password is weak. Please choose a stronger one for better security.",
  USER_ALREADY_EXIST_MESSAGE: "Oh dear! It seems like this user email or username already exists. Please try a different one.",
  USERNAME_PASSWROD_MUST_MESSAGE: "Hey there! Both username and password are required fields. Please provide them.",
  USERNAME_INVALID: "Oops! The username you entered is invalid. Please try again.",
  EMAIL_SUCCESFULLY_SENT: "Great news! Your email has been sent successfully.",
  INVALID_OTP: "Oops! The OTP you entered is invalid. Please double-check and try again.",
  OTP_VERIFIED_SUCCESSFULLY: "Hooray! Your OTP has been verified successfully.",
  EMAIL_TOKEN_EXPIRED: "Oh no! The verification link has expired. Please request a new one.",
  USERNAME_NOT_FOUND: "Sorry, we couldn't find the username you provided. Please check and try again.",
  USER_BANNED: "We're sorry, but we cannot log you in at the moment. Please try again later.",
  CARD_NUMBER_INVALID_MESSAGE: "Uh-oh! The card number you entered is invalid. Please double-check and try again.",
  CARD_NAME_INVALID_MESSAGE: "Oops! The card name you entered is invalid. Please try again.",
  CARD_NO_ALREADY_EXIST_MESSAGE: "Oh no! It looks like this card number already exists. Please use a different one.",
  CARD_SUCCESFULLY_ADDED_MESSAGE: "Congratulations! Your card has been successfully added.",
  PASSWORD_MISMATCH: "Oh dear! The new password and confirm password must match. Please try again.",
  PASSWORD_UPDATED: "Success! Your password has been changed successfully.",
  OLD_PASSWORD_INVALID: "Oops! The old password you entered is invalid. Please try again.",
  ALREADY_USED_PASSWORD: "Sorry, but you have already used this password. Please choose a new one.",
  NOT_AUTORIZED: "Oops! You are not authorized to perform this action. Please contact support for assistance.",
  EMAIL_SENT: "Email successfully send in your account",
  EMAIL_NOT_VERIFIED: 'Email not Verified',
  VERIFICATION_EMAIL_SUBJECT: 'Please verify your account',
  VERIFICATION_FORGOT_SUBJECT: 'Please reset your account',
  VERIFICATION_TEAM_SUBJECT: "Please accept your invitaion",
  INVALID_VERIFICATION_TOKEN: 'Invalid verification token',
  VARIFICATION_TOKEN_EXPIRE: 'Verification token has expired',
  VERIFICATION_SUCCESSFULL: 'Email verified successfully',
  SEND_EMAIL_FAILED: 'Send Email Failed',
  TOKEN_VERIFY_SUCCESS: 'Token verify successfull',
  TOKEN_NOT_VERIFIED: 'Token Invalid',
  TOKEN_EXPIRED: 'Token is expired',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully! Please Login in',
  AUTHORIZATION_INVALID: 'Authorization Token not provided!',
  AUTHORIZATION_TOKEN_NOT_FOUND: 'Authentication token not provided!',
  AUTHORIZATION_TOKEN_INVALID: "Please Login Before access this page!",
  REFRESH_TOKEN_EXPIRED: 'Refresh token is expired!',
  REFRESH_TOKEN_INVALID: 'Refresh token is invalid!',
  NEW_TOKEN_GENERATE_SUCCESS: 'New Token generated',
  STRIPE_PAYMENT_SUCCESS: 'Payment successfully Done!',
  SUBSCRIPTION_NOT_EXIST: 'user Not subscribed',
  SUBSCRIPTION_CREATED_SUCCESS: 'Subscribed successfully',
  SUBSCRIPTION_CREATED_FAILED: 'Your subscription has been canceled due to reaching the monthly limit',
  SUBSCRIPTION_ALREADY_EXISTS: 'Subscription already exist',
  COMPANY_NOT_FOUND: 'Company not  found',
  SUBSCRIPTION_RETRIVED_FAILED: 'Subscription retrived failed',
  COMPANY_DATA_CREATED: 'Company data created',
  COMPANY_DATA_UPDATED: 'Company data updated',
  ACCOUNT_NOT_ACTIVE: 'Your Account is not active!',
  TEAM_VERIFICATION: 'Please set your passwrod',
  ROLES_NOT_FOUND: 'Role not Found',
  ROLES_GET_SUCCESS: 'Roles get successfully',
  COMPANY_GET_USER_SUCCESS: 'users get successfully',
  ROLES_UPDATED_SUCCESS: 'Roles Updated Successfully',
  USER_NOT_FOUND_OR_ROLE_SAME: 'User not found or role is same',
  ROLE_DELETE_SUCCESS: 'Role Delete Successfully',
  ONLY_OWNER_AND_ADMINISTRATOR_CAN_UPDATE_ROLE: 'Only owner or administrator can update roles',
  ONLY_OWNER_AND_ADMINISTRATORCAN_DELETE_ROLES: 'Only owner or administrator can delete roles',
  ONLY_OWNER_AND_ADMINISTRATOR_CAN_CHANGE_STATUS: 'Only owner or administrator can change status',
  USER_NOT_FOUND_OR_ACOUNT_OWNER: "Sorry you can't disable owner account ",
  USER_STATUS_UPDATED: 'User status updated',
  USER_COULD_NOT_DELETE: 'User could not delete',
  USER_DELETED_SUCCESSFULL: 'Account permanentaly deleted Successfull',
  EMAIL_VERIFICATION_LINK: 'Email verification Link sent',
  COMPANY_USER_EMAIL_VERIFICATION_FAILED: 'Email Verificaiton Failed Please contact your company owner or administrator.',
  EMAIL_VERIFICATION_FAILED: 'Account email verification failed',
  STIPE_CUSTOMER_UPDATE_SUCCESS: 'stripe customer update success',
  COULD_NOT_UPDATE_CUSTOMER_DETAILS: 'could not update customer details'
};

export default Messages